name: GTest tests

on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # TODO: Revert back to Release once the issue is fixed
  # https://github.com/actions/runner-images/issues/10004
  # BUILD_TYPE: Release
  BUILD_TYPE: Debug
  CMAKE_BUILD_PARALLEL_LEVEL: 2

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [ubuntu-latest, windows-latest]
          # os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -qq libusb-1.0-0-dev

      - name: Install osx dependencies
        if: matrix.os == 'macos-latest'
        run: brew install libusb

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_SHARED_LIBS=OFF -DENABLE_UNIT_TESTS=on -DBUILD_GUI=off

      - name: Build tests
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target gtest-runner

      - name: Run tests (Linux)
        if: matrix.os != 'windows-latest'
        run: ${{github.workspace}}/build/bin/gtest-runner

      - name: Run tests (Windows)
        if: matrix.os == 'windows-latest'
        run: ${{github.workspace}}/build/bin/${{env.BUILD_TYPE}}/gtest-runner.exe
