name: Packaging

on:
  workflow_dispatch:
  push:
    branches: [stable]
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CMAKE_OPTIONS:

jobs:
  debian:
    name: Package Debian
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
      # need subdirectory, because building packages will place them one directory up
        with:
          path: 'source'

      - name: Install GNURadio
        if: ${{ matrix.os != 'ubuntu-20.04'}} # 20.04 has GNURadio 3.8.1, it's python bindings are not using pybind11, so not compatible
        run: |
          sudo apt-get update
          sudo apt-get install -qq gnuradio-dev

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install debhelper dh-python dkms
          sudo ${{github.workspace}}/source/install_dependencies.sh

      # dh-dkms was split into separate package
      - name: Install dh-dkms
        if: ${{ matrix.os == 'ubuntu-24.04'}}
        run: |
          sudo apt-get install dh-dkms

      - name: Build
        run: |
          cd source
          dpkg-buildpackage --no-sign

      # - name: Archive packaging artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: debian-packages
      #     retention-days: 3
      #     path: |
      #       ${{github.workspace}}/*.tar.xz
      #       ${{github.workspace}}/*.dsc
      #       ${{github.workspace}}/*.deb
      #       ${{github.workspace}}/*.ddeb
